### ISSUE TITLE
False positiv error if matrix entry is list of objects

### ISSUE THREAD

**Issue by s-weigand** [Lona/vscode-github-actions#1]
First of all thank you very much for this great extension.

I'm getting an linting error on the object in my workflow, if a matrix entry is a list of objects (`Incorrect type. Expected "string".`). 
But this is supported by the workflow and also works.

```yaml
    strategy:
      matrix:
        python-version: [3.6, 3.7]
        version_combinations:
          [
            { "django": 1.11, "cms": 3.4 },
            { "django": 1.11, "cms": 3.5 },
            { "django": 1.11, "cms": 3.6 },
            { "django": 1.11, "cms": 3.7 },
            { "django": "2.0", "cms": 3.6 },
            { "django": "2.0", "cms": 3.7 },
            { "django": 2.1, "cms": 3.7 },
            { "django": 2.1, "cms": 3.6 },
            { "django": 2.2, "cms": 3.7 },
          ]
```

I don't know why this is happening since [in the schema](https://github.com/Lona/vscode-github-actions/blob/26e584583239a8acb8b286b2ef2b06b6ff1b1184/schemas/workflow.schema.json#L276) `matrix` is defined as `object`, which should also allow entrys of type `object[]`.

**Comment by mathieudutour** [comment]
I just published `v2.2.4`. Could you try it and let me know?

Otherwise we might need to add some tests (examples to test against the schemas) 😬. We should probably do that anyway

**Comment by s-weigand** [comment]
Sadly the problem still persists 😢 
![gh-action-false-positiv-lint](https://user-images.githubusercontent.com/9513634/69861539-e1bfe500-1298-11ea-96ee-fbd211a34e12.jpg)

**Comment by mathieudutour** [comment]
so I added a minimal test case that looks similar to yours: https://github.com/Lona/vscode-github-actions/blob/master/schemas/__tests__/cases/1.yml and it seems to work.

Could you open a PR with a case that fails?

**Comment by s-weigand** [comment]
After 3 hours of messing around with this, I decided to delete my fork again, since there is nothing I can contribute that way.
The whole bloody problem is that `vscode-yaml` uses the schema from [`SchemaStore`](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/github-workflow.json), which doesn't allow object entries.
Always good when something is doing something for you w/o you knowing it.....

```
expect(received).toMatchSchema(schema)

    received
      .jobs['test'].strategy.matrix['version_combinations'][0] should be string
      .jobs['test'].strategy.matrix['version_combinations'][0] should be number
      .jobs['test'].strategy.matrix['version_combinations'][0] should match exactly one schema in oneOf
      .jobs['test'].strategy.matrix['version_combinations'][1] should be string
      .jobs['test'].strategy.matrix['version_combinations'][1] should be number
      .jobs['test'].strategy.matrix['version_combinations'][1] should match exactly one schema in oneOf
      .jobs['test'].strategy.matrix['version_combinations'][2] should be string
      .jobs['test'].strategy.matrix['version_combinations'][2] should be number
      .jobs['test'].strategy.matrix['version_combinations'][2] should match exactly one schema in oneOf
      .jobs['test'].strategy.matrix['version_combinations'][3] should be string
      .jobs['test'].strategy.matrix['version_combinations'][3] should be number
      .jobs['test'].strategy.matrix['version_combinations'][3] should match exactly one schema in oneOf
      .jobs['test'].strategy.matrix['version_combinations'][4] should be string
      .jobs['test'].strategy.matrix['version_combinations'][4] should be number
      .jobs['test'].strategy.matrix['version_combinations'][4] should match exactly one schema in oneOf
      .jobs['test'].strategy.matrix['version_combinations'][5] should be string
      .jobs['test'].strategy.matrix['version_combinations'][5] should be number
      .jobs['test'].strategy.matrix['version_combinations'][5] should match exactly one schema in oneOf
      .jobs['test'].strategy.matrix['version_combinations'][6] should be string
      .jobs['test'].strategy.matrix['version_combinations'][6] should be number
      .jobs['test'].strategy.matrix['version_combinations'][6] should match exactly one schema in oneOf
      .jobs['test'].strategy.matrix['version_combinations'][7] should be string
      .jobs['test'].strategy.matrix['version_combinations'][7] should be number
      .jobs['test'].strategy.matrix['version_combinations'][7] should match exactly one schema in oneOf
      .jobs['test'].strategy.matrix['version_combinations'][8] should be string
      .jobs['test'].strategy.matrix['version_combinations'][8] should be number
      .jobs['test'].strategy.matrix['version_combinations'][8] should match exactly one schema in oneOf
```

So, IMO there would be 2 solutions:
1. Overwrite the entry name (can't find it) of the other version and maintain your own schema.
2. Make a PR to [`SchemaStore`](https://github.com/SchemaStore/schemastore) to fix this issue, which basically renders the extension pointless, sorry for that 😖.

**Comment by s-weigand** [comment]
For overwriting there is already an open issue, with a similar problem.
And it doesn't seem to be possible at the moment.
https://github.com/redhat-developer/vscode-yaml/issues/245

**Comment by mathieudutour** [comment]
> Make a PR to SchemaStore to fix this issue, which basically renders the extension pointless, sorry for that 😖

That's probably the way to go!

**Comment by mathieudutour** [comment]
https://github.com/SchemaStore/schemastore/pull/872

**Comment by s-weigand** [comment]
Cool, thank you for doing this, I saw the `schema.json` files the first time before opening this issue.
One little think so, I don't see changes in the allowed values of `matrix` in the PR, which this issue was initially about.
Or is that what [`"$ref": "#/definitions/configuration"`](https://github.com/SchemaStore/schemastore/blob/abfdd8608c7b03cfa73b249ae9f46799e37c07a5/src/schemas/json/github-workflow.json#L985) does?

**Comment by mathieudutour** [comment]
That’s what it does indeed

**Comment by s-weigand** [comment]
Ok thanks for explain that to nooby me 😄

**Comment by mathieudutour** [comment]
Thanks for finding out what was causing the issue :)

**Comment by s-weigand** [comment]
Well, it wasn't completely altruistic since I also use the tool 😋 

__Quick sidenode:__

While this is a valid entry in the workflow:
```yaml
      matrix:
        foo: [ { "bar": 1.1, "baz": "bazz" },]
```

This isn't:
```yaml
      matrix:
        foo: { "bar": 1.1, "baz": "bazz" }
```

I'm not sure if the schema with your fixes gets this right, since `"$ref": "#/definitions/configuration"` is used recursively and on the top level this wouldn't show the error.

**Comment by mathieudutour** [comment]
True.

But when I try to create a workflow using the GitHub UI with:
```yaml
name: CI

on: [push]

jobs:
  
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.7]
        version_combinations:
          - { "django": 1.11, "cms": 3.6 }
          - { "django": 1.11, "cms": 3.7 }
          - { "django": "2.0", "cms": 3.6 }
          - { "django": "2.0", "cms": 3.7 }
          - { "django": 2.1, "cms": 3.7 }
          - { "django": 2.1, "cms": 3.6 }
          - { "django": 2.2, "cms": 3.7 }
          

    steps:
    - name: Run a one-line script
      run: echo Hello, world!
```
it shows an error: `Matrix options must only contain primitive values`. So it seems like arrays of objects are forbidden?

**Comment by s-weigand** [comment]
Well, it works ..., but I'm not sure if by accident or design. I hope the later.
Maybe the specs for the editor weren't yet updated?

For sure it is allowed for the keys `include` and `exclude` ([see example](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix)).

Maybe this also allows an unintended proper parsing of my use case.

**Comment by s-weigand** [comment]
Maybe they should be recommended to use the schema of the SchemaStore, for their editor to unify the effort?
